### ISSUE TITLE
derive Alt

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [ekmett/semigroupoids#135]
It would be nice to be able to derive Alt  but I get this error

```
\> import Data.Functor.Alt as A
\> newtype WE a b = WE (Either a b) deriving (Alt)

<interactive>:2:44: error:
    _ Couldn't match type: Either a
                     with: WE a
        arising from the coercion of the method _many_
          from type _forall a1.
                     Applicative (Either a) =>
                     Either a a1 -> Either a [a1]_
            to type _forall a1. Applicative (WE a) => WE a a1 -> WE a [a1]_
    _ When deriving the instance for (Alt (WE a))

<interactive>:2:44: error:
    _ Couldn't match type: Either a
                     with: WE a
        arising from the coercion of the method _some_
          from type _forall a1.
                     Applicative (Either a) =>
                     Either a a1 -> Either a [a1]_
            to type _forall a1. Applicative (WE a) => WE a a1 -> WE a [a1]_
    _ When deriving the instance for (Alt (WE a))
```

**Comment by RyanGlScott** [comment]
This is a known GHC limitation: see https://gitlab.haskell.org/ghc/ghc/-/issues/20815.

**Comment by BebeSparkelSparkel** [comment]
As a stopgap could be

```haskell
class Alt' f where
  alt :: f a -> f a -> f a
class Alt' f => Alt f where
  (<!>) :: f a -> f a -> f a
  (<!>) = alt
  some ...
  many ...
```

Now newtypes can basically derive it with

```haskell
newtype WE a b = WE (Either a b) deriving (Alt')
instance Alt (WE a)
```

**Comment by BebeSparkelSparkel** [comment]
@RyanGlScott Looking at the GHC issue it appears that there has not been progress on them lately. Any thoughts on the stopgap?

**Comment by RyanGlScott** [comment]
My personal two cents (@ekmett may have different thoughts): I'm not keen on changing the class hierarchy just for the sake of working around a GHC limitation. In my experience, rearranging class APIs almost invariably inflicts pain upon downstream users by breaking existing code. I'd like to avoid that situation unless there is a consensus that that is the design that a bulk of the users want.

**Comment by RyanGlScott** [comment]
Note that https://gitlab.haskell.org/ghc/ghc/-/issues/20815 has been fixed upstream, so it will be possible to derive `Alt` using `GeneralizedNewtypeDeriving` in a future GHC release.
