### ISSUE TITLE
Suggestion: move Foldable1 and Traversable1 to the "semigroups" package

### ISSUE THREAD

**Issue by nikita-volkov** [ekmett/semigroupoids#16]

**Comment by ekmett** [comment]
The problem with this proposal is that the classes we need to take advantage of them and write many of the methods for them `Apply` and `Bind`, live here.

`Data.Foldable` and `Data.Traversable` provide a ton of combinators in terms of `Applicative` and `Monad`. These modules can't provide a comparable API without pulling large chunks of this package along for the ride.
