### ISSUE TITLE
Does not compile with GHC-7.11

### ISSUE THREAD

**Issue by Skyfold** [ekmett/semigroupoids#25]
Basically GHC has become stricter and needs to explicitly enable language extensions in some cases that weren't needed previously. GHC will tell you which extension to enable. See also #8883 for details.

In this case you just need to add ConstrainedClassMethods. Mostly this is just to let you know (Since this was added in GHC-7.10)

src/Data/Functor/Alt.hs:85:3:
    Constraint ‘Applicative f’ in the type of ‘some’
      constrains only the class type variables
    Use ConstrainedClassMethods to allow it
    When checking the class method:
      some :: forall (f :: * -> *).
              Alt f =>
              forall a. Applicative f => f a -> f [a]
    In the class declaration for ‘Alt’

src/Data/Functor/Alt.hs:90:3:
    Constraint ‘Applicative f’ in the type of ‘many’
      constrains only the class type variables
    Use ConstrainedClassMethods to allow it
    When checking the class method:
      many :: forall (f :: * -> *).
              Alt f =>
              forall a. Applicative f => f a -> f [a]
    In the class declaration for ‘Alt’

**Comment by peti** [comment]
I also have trouble compiling semigroupoids-4.3 with ghc-7.11.20150402. A complete build log is available at http://hydra.cryp.to/build/729176/nixlog/1/raw.

**Comment by Skyfold** [comment]
Should have closed this awhile ago. If you clone this repo it will compile with GHC-7.10 and the current GHC HEAD. The version on Hackage just has not been updated so you still get the error.

**Comment by glguy** [comment]
For reference

https://github.com/ekmett/semigroupoids/commit/9d47b9f6591848543c71f901c581422d4b80a3de

**Comment by Skyfold** [comment]
This has been updated on Hackage
