### ISSUE TITLE
4.5 seems to have broken profunctor

### ISSUE THREAD

**Issue by irickt** [ekmett/semigroupoids#29]
New Haskeller here ...

I was trying to install BlogLiterally just now and got this with 4.5:

    src/Data/Profunctor/Collage.hs:27:37:
        In module ‘Data.Semigroupoid.Coproduct’:
        ‘L’ is a data constructor of ‘Coproduct’
        To import it use
        ‘import’ Data.Semigroupoid.Coproduct( Coproduct( L ) )
        or
        ‘import’ Data.Semigroupoid.Coproduct( Coproduct(..) )

    src/Data/Profunctor/Collage.hs:27:40:
        In module ‘Data.Semigroupoid.Coproduct’:
        ‘R’ is a data constructor of ‘Coproduct’
        To import it use
        ‘import’ Data.Semigroupoid.Coproduct( Coproduct( R ) )
        or
        ‘import’ Data.Semigroupoid.Coproduct( Coproduct(..) )

I removed 4.5 leaving 4.3 and it compiles.

Edit: GHC 7.10.1

**Comment by ekmett** [comment]
There was a short window after upload when the version bounds for profunctor weren't locked down tight enough. This is now fixed.
