### ISSUE TITLE
doctest run failure

### ISSUE THREAD

**Issue by snoyberg** [ekmett/semigroupoids#34]
```
Test suite doctests: RUNNING...

/tmp/stackage-build1/semigroupoids-4.3/src/Data/Functor/Plus.hs:28:8:
    Ambiguous module name ‘Control.Monad.Trans.List’:
      it was found in multiple packages:
      transformers-0.4.2.0@trans_ALYlebOVzVI4kxbFX5SGhm List-0.5.2@List_EZ7COmjkRvhIK3FoA6CYQW
Test suite doctests: FAIL
Test suite logged to: /home/stackage/work/logs/nightly/semigroupoids-4.3/test-run.out
```

**Comment by Taneb** [comment]
I am quite surprised at this; this library does not depend on List whatsoever, so I don't see how this is occurring. I'd suggest that it's a problem with doctest not sandboxing its testing as much as cabal sandboxes when during "cabal install" (or even "cabal repl", to which I assumed doctest was using something similar)

**Comment by ekmett** [comment]
This issue seems to be fixed in 5.

Nowadays `doctests` support is handled through a custom script that hides all packages except the dependencies of this package, so contamination from third-party libraries I don't use shouldn't affect me any more.

Let me know if this is still happening.
