### ISSUE TITLE
Add an identity to get a category

### ISSUE THREAD

**Issue by treeowl** [ekmett/semigroupoids#41]
This might already exist somewhere, but I couldn't find it. I'm not at all committed to these names.

``` haskell
data Categorize s a b where
  Id :: Categorize s a a
  Embed :: s a b -> Categorize s a b

instance Semigroupoid s => Semigroupoid (Categorize s) where
  Id `o` y = y
  x `o` Id = x
  Embed x `o` Embed y = Embed (x `o` y)

instance Semigroupoid s => Category (Categorize s) where
  id = Id
  (.) = o
```

**Comment by treeowl** [comment]
Since `Option` is in `semigroups`, I think `semigroupoids` is likely the right place for this thing, whatever it and its constructors should be called.

**Comment by ekmett** [comment]
I have no objection to adding such a construction in principle. Not sure about the name.

**Comment by treeowl** [comment]
Do you have better names?

**Comment by treeowl** [comment]
Bump! I want this for a fork of type-aligned I'm working on. Any chance you can pick a name and stick it in? Also, it supports the following eliminator, which should therefore be included.

```haskell
categorize :: (a ~ b => r) -> (s a b -> r) -> Categorize s a b -> r
categorize r _ Id = r
categorize _ f (Embed x) = f x
```
