### ISSUE TITLE
No instance for (Bifoldable Tagged)

### ISSUE THREAD

**Issue by thomie** [ekmett/semigroupoids#48]
Trying to compile `semigroupoids-5.1` with GHC HEAD (ghc-8.1.20160720), I get:

```
src/Data/Semigroup/Foldable/Class.hs:99:10: error:
    • No instance for (Bifoldable Tagged)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Bifoldable1 Tagged’
```

I have `bifunctors-5.4.1` and `tagged-0.8.4` installed (latest versions from Hackage).

https://github.com/ekmett/bifunctors/issues/49 is related.

**Comment by RyanGlScott** [comment]
Ack, sorry for dropping the ball on that. I've uploaded [`tagged-0.8.5`](http://hackage.haskell.org/package/tagged-0.8.5) to Hackage, which should resolve this particular issue.

**Comment by thomie** [comment]
Thanks. It works.
