### ISSUE TITLE
Add some of these functions to Data.Semigroup.Foldable

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/semigroupoids#49]
Some `Foldable` functions are missing from `Data.Semigroup.Foldable`. See this [repo](https://github.com/arkeet/difference/blob/0f0e14f51cf1ecd7ebf2d8c52204bd91ae3b2969/src/Data/Semigroup/Difference.hs), do any of them belong there?

```haskell
foldr1m :: Foldable1 t => (a -> Maybe b -> b) -> (t a -> b)
foldr1m f = unimprove . foldMap1 (diffMaybe . f)

foldr1 :: Foldable1 t => (a -> a -> a) -> (t a -> a)
foldr1 f = unimprove . foldMap1 (\a -> Diff (f a) a)

foldl1m :: Foldable1 t => (Maybe b -> a -> b) -> (t a -> b)
foldl1m f = unimprove . getDual . foldMap1 (Dual . diffMaybe . flip f)

foldl1 :: Foldable1 t => (a -> a -> a) -> (t a -> a)
foldl1 f = unimprove . getDual . foldMap1 (\a -> Dual $ Diff (flip f a) a)

toList1 :: Foldable1 t => t a -> NonEmpty a
toList1 = foldr1m (\a -> maybe (a :| []) (a <|))
```

**Comment by recursion-ninja** [comment]
I think `toList1` would be more appropriately named `toNonEmpty`.

Otherwise these are all very useful additions!

**Comment by Icelandjack** [comment]
Ah obviously, shall I make a patch?

**Comment by recursion-ninja** [comment]
Sure, or I can attempt to do it on Sunday.

**Comment by Icelandjack** [comment]
That would be great! I'll leave it to you :+1:

**Comment by recursion-ninja** [comment]
We'll have exclude `foldl1` & `foldr1` from the `Foldable1` class since they are already part of the "super class" `Foldable`. In principle, they should be removed from `Foldable` and be only defined for `Foldable1`, but alas, the Haskell ecosystem is not perfect.

**Comment by Icelandjack** [comment]
How about functions from [here](https://github.com/bfpg/2012-10-semigroups-monoids-trees/blob/54bce1edc1d0259d67edfdf577d55b21fe37e2d8/code/Monoid.hs#L175)

```haskell
import qualified Data.Semigroup as S

minimum1 :: (Ord a, Foldable1 t) => t a -> a
minimum1 = S.getMin . foldMap1 S.Min

maximum1 :: (Ord a, Foldable1 t) => t a -> a
maximum1 = S.getMax . foldMap1 S.Max

head1 :: Foldable1 t => t a -> a
head1 = S.getFirst . foldMap1 S.First

last1 :: Foldable1 t => t a -> a
last1 = S.getLast . foldMap1 S.Last
```

maybe this (`argmin`/`argmax` assumes [`#13572`](https://ghc.haskell.org/trac/ghc/ticket/13572), is inspired by [this](https://github.com/energyflowanalysis/efa-2.1/blob/3eb86c0b6b2d2fb66cd5b76ce5c0437d42f8cdf8/sandbox/delaunay/HalfPlaneMap.hs#L181))

```haskell
foo :: (Foldable1 t, S.Semigroup a) => t (Maybe a) -> Maybe a
foo = S.getOption . foldMap1 S.Option

argmin :: Ord k => Foldable1 f => (a -> k) -> (f a -> a)
argmin f = minValue . foldMap1 (\a -> ArgMin (f a) a)

argmax :: Ord k => Foldable1 f => (a -> k) -> (f a -> a)
argmax f = maxValue . foldMap1 (\a -> ArgMax (f a) a)
```

**Comment by recursion-ninja** [comment]
`minimum1` & `maximum1` are also defined in the "super-class" `Foldable` as `minimum` & `maximum`. These are generally unsafe in the `Foldable` class, but are safe for data types which are also `Foldable1`. 

`head1` & `last1` are a bit more nuanced. While we definitely _could_ define them for any `Foldable1`, it might be more appropriate to call `toNonEmpty` and the use the safe versions of [`head`](https://hackage.haskell.org/package/semigroups-0.18.1/docs/Data-List-NonEmpty.html#v:head) and [`tail`](https://hackage.haskell.org/package/semigroups-0.18.1/docs/Data-List-NonEmpty.html#v:tail) from `Data.List.NonEmpty`.

I think `argmin` could be defined in terms of [`minimumBy`](https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Foldable.html#v:minimumBy) and [`comparing`](https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Ord.html#v:comparing). `argmax` should be definable in a similar way using [`maximumBy`](https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Foldable.html#v:maximumBy). Since these are already part of the `Foldable` "super-class" of `Foldable1`, Im not sure there's much utility in adding functions like `argmin` & `argmax`.

**Comment by Icelandjack** [comment]
People presumably import `Data.Semigroup.Foldable` to work with non-empty structures, but relying on `Foldable` methods puts the burden of checking non-emptiness on the programmer.

A user will have to identify partial `Foldable`-methods and restrict them locally with the partial `maximum` in scope (I don't want to rely on not forgetting the `1`!):

```haskell
maximum1 :: (Foldable1 f, Ord a) => f a -> a
maximum1 = maximum
```

I'm okay with names like `foldr1`, `foldl1` clashing (they should be in `Foldable1` to begin with as you say) and exporting `maximum1`, ... gives me power as a programmer to hide partial functions in favour of the total ones:

```haskell
import Data.Semigroup.Foldable (foldr1, maximum1)
import Data.Foldable hiding (foldr1, maximum)
```

It also tells users they are an option in the first place, which may not be obvious to new users of the package. I want to rely on the type system for these things

I don't really care about `argmin`, `argmax` but I figured I would propose one for each semigroup in `Data.Semigroup` :smile:

**Comment by Icelandjack** [comment]
> `head1` & `last1` are a bit more nuanced. While we definitely could define them for any `Foldable1`, it might be more appropriate to call `toNonEmpty` and the use the safe versions of `head` and `tail` from `Data.List.NonEmpty`.

Why not the other way 'round? If you already have `Foldable1` why not make use of it

**Comment by Icelandjack** [comment]
Maybe we can make `Foldable1` versions of the monadic folds as well: `foldM`, .. thoughts?

**Comment by recursion-ninja** [comment]
I think that `foldr1M :: (Foldable a, Monad m) => (a -> a -> m a) -> t a -> m a` would be appropriate along with a `foldl1M` with the function argument permuted. We might only need `Applicative` and not a full `Monad`, I would have to explore that a little bit.

**Comment by Icelandjack** [comment]
We have `NonEmpty` / `Semigroup` in *base*, should I make a migration proposal to add `Foldable1` and `Traversable1`?

It would be great to get rid of `foldr1`, `foldl1` as well as other partial functions from there.

**Comment by recursion-ninja** [comment]
I gave `head1` & `tail1` some thought. What if we labeled them `genericHead` and `genericTail` so they shared a similar nomenclature to the generic list functions here: 

https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-List.html#g:26

I believe `Foldable1` is the least restrictive constraint to provide safe "head" and "tail" operations.

**Comment by phadej** [comment]
FWIW, `head1` and `tail1` should probably be a members of `Foldable1`; as for many tree structures (or snoc-lists) both (or other one) can be defined more efficiently. I guess it's the reasoning why `Foldable1` class is big too.

I'm neutral on `Foldable1` and `Traversable1` moving to `base`. Latter will pull in also `Data.Functor.Apply`; I'm slightly :+1: for it to eventually become superclass of `Applicative`, but it would be great to figure out some convenience mechanism so the migration would be as simple as possible (there're plenty of `Applicative`s). I guess that's the reason why it's not proposed, nobody yet knows the good ending to the story.

**Comment by Icelandjack** [comment]
> I gave `head1` & `tail1` some thought. What if we labeled them `genericHead` and `genericTail` so they shared a similar nomenclature to the generic list functions here:

I don't see how that nomenclature is similar, in fact the `generic*` functions are generic in an integral value which is not similar to `head1`, `last1`.

Appending `1` feels simple and more consistent to me and I worry they won't see as much usage if we go with `generic*` names.

**Comment by Icelandjack** [comment]
> FWIW, `head1` and `tail1` should probably be a members of `Foldable1`;

Yeah

> I'm neutral on `Foldable1` and `Traversable1` moving to base. 

I got the ball rolling to only include `Foldable1` in base ([`#13573` — Add `Foldable1` to base](https://ghc.haskell.org/trac/ghc/ticket/13573)), it does *not* include `Traversable1` which is not as useful (imo).

I don't dare propose anything wrt `Apply` :dizzy_face:

**Comment by phadej** [comment]
@Icelandjack as that's a `base` change, you should send mail to `libraries@`.

**Comment by Icelandjack** [comment]
Was hoping to get some feedback on the idea before going to the mailing lists (I don't like using them for discussions)

**Comment by Icelandjack** [comment]
Then again just adding it to *base* is not a big change so I can start a thread, it would be nice to have agreement on the method names though.

**Comment by chessai** [comment]
I've committed a differential for adding Foldable1 to base: ​https://phabricator.haskell.org/D4812

**Comment by RyanGlScott** [comment]
`Foldable1` is now defined in `base`, and `semigroupoids` simply re-exports `Foldable1` from `base`. As such, this issue isn't really in scope for `semigroupoids` anymore. Closing.

**Comment by phadej** [comment]
FWIW, variants of these functions *are* in the `base` version. `foldr1m` is `foldrMap1` e.g.
