### ISSUE TITLE
concat1 and concatMap1

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/semigroupoids#53]
Like #49 but I don't want to clutter.

I needed `concatMap1` just now. Would people be against adding

```haskell
concat1 :: Foldable1 f => f (NonEmpty a) -> NonEmpty a
concat1 = concatMap1 id

concatMap1 :: forall f a b. Foldable1 f => (a -> NonEmpty b) -> (f a -> NonEmpty b)
concatMap1 f = foldr1m h where

  h :: a -> Maybe (NonEmpty b) -> NonEmpty b
  h a Nothing  = f a
  h a (Just x) = f a <> x
```

Similar functions exist as comments in [`Data.Semigroup.Foldable`](https://hackage.haskell.org/package/semigroupoids-5.2/docs/src/Data-Semigroup-Foldable.html):

```haskell
concat1    :: Foldable1 t => t (Stream a) -> Stream a
concatMap1 :: Foldable1 t => (a -> Stream b) -> t a -> Stream b
```

**Comment by bucklereed** [comment]
Aren't those just `fold1` and `foldMap1`, specialised to `NonEmpty a` for the semigroup?

**Comment by Icelandjack** [comment]
You're right and same with `Stream` examples since `Foldable1 Stream`. 

`Data.Foldable` does include

```haskell
concat :: Foldable t => t [a] -> [a]
concatMap :: Foldable f => (a -> [b]) -> (t a -> [b])
```

so it may be worth adding them still (but obviously not as important)

```haskell
concat1 :: Foldable1 f1 => f1 (NonEmpty a) -> NonEmpty a
concat1 = fold1

concatMap1 :: Foldable1 f1 => (a -> NonEmpty b) -> (f1 a -> NonEmpty b)
concatMap1 = foldMap1
```

**Comment by RyanGlScott** [comment]
`Foldable1` is now defined in `base`, and `semigroupoids` simply re-exports `Foldable1` from `base`. As such, this issue isn't really in scope for `semigroupoids` anymore. Closing.
