### ISSUE TITLE
Issue with GHC 8.2.1-rc2 and LTS 8.15

### ISSUE THREAD

**Issue by varosi** [ekmett/semigroupoids#54]
```
C:\Users\Me\AppData\Local\Temp\stack13816\semigroupoids-5.1\Setup.lhs:8:31: error:
        Module
        `Distribution.Package'
        does not export
        `PackageName(PackageName)'
      |
    8 | import Distribution.Package ( PackageName(PackageName), PackageId, InstalledPackageId, packageVersion, packageName )
      |                               ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
What you're describing shouldn't be possible with the way the current `Setup` script is designed. Can you describe how you're building `semigroupoids`, including any settings you're setting in `stack.yaml`?

**Comment by RyanGlScott** [comment]
I'm going to close this, as I cannot figure out how to reproduce the issue. Please re-open if you can tell me otherwise.
