### ISSUE TITLE
Bump dependency on tagged

### ISSUE THREAD

**Issue by jakubdaniel** [ekmett/semigroupoids#62]
`(Bifoldable Tagged)` instance is missing in `tagged-0.7.3`. At least `semigroupoids-0.5.2` is affected when compiled with `ghc-8.2.1`. `tagged-0.8.5` is fine.

**Comment by RyanGlScott** [comment]
Thanks. I've revised the Hackage bounds to depend on `tagged-0.8.5` as the minimum (and pushed a corresponding change to `master` in https://github.com/ekmett/semigroupoids/commit/96a5fd8dfa2b370e7750a26eef3c1aac2fbd3115).
