### ISSUE TITLE
Combining MaybeApply f and f

### ISSUE THREAD

**Issue by quasicomputational** [ekmett/semigroupoids#66]
I've found these combinators to be very handy:

```
(<.*>) :: (Apply f) => f (a -> b) -> MaybeApply f a -> f b
ff <.*> MaybeApply (Left fa) = ff <.> fa
ff <.*> MaybeApply (Right a) = ($ a) <$> ff
infixl 4 <.*>

(<*.>) :: (Apply f) => MaybeApply f (a -> b) -> f a -> f b
MaybeApply (Left ff) <*.> fa = ff <.> fa
MaybeApply (Right f) <*.> fa = f <$> fa
infixl 4 <*.>
```

They're useful for defining Traversable1/Bitraversable1 for types that have fields that can be empty, e.g.:

```
data Foo a = Foo (Maybe a) (Maybe a) (Maybe a) a [a]

instance Traversable1 Foo where
  traverse1 f (Foo ma mb mc a as) = Foo <$> traverse f ma <*> traverse f mb <*> traverse f mc <*.> f a <.*> traverse f as
```

Should they be added to Data.Functor.Apply?

**Comment by michaelpj** [comment]
Found myself wanting this today, thanks for the functions! Would be nice to have them in the package.

**Comment by michaelpj** [comment]
For the curious, this doesn't work quite as posted, but here's a working version: https://gist.github.com/michaelpj/b731fd368d066b7f9d78318b96b3690c
