### ISSUE TITLE
GHC-7.4.2: src/Data/Functor/Bind/Class.hs:441:16:     Not in scope: type constructor or class `Down'

### ISSUE THREAD

**Issue by phadej** [ekmett/semigroupoids#72]
How to resolve:
- bump lower bound for `base` or
- CPP
?

culprit most likely: https://github.com/ekmett/semigroupoids/commit/dd4c121c2665df4a2492948fccdb8479a49767d6

**Comment by RyanGlScott** [comment]
I would go with a CPP approach: prior to `base-4.6`, we import `Down` from `GHC.Exts` (its home prior to `Data.Ord`).

**Comment by phadej** [comment]
Oh, I didn't know we have `Down` there. I'll make a PR
